// banksStore.js
import create from 'zustand';

const useBanksStore = create((set) => ({
  banks: [
    { id: 1, name: "Bank Mandiri" },
    { id: 2, name: "Bank Rakyat Indonesia (BRI)" },
    { id: 3, name: "Bank Central Asia (BCA)" },
    { id: 4, name: "Bank Negara Indonesia (BNI)" },
    { id: 5, name: "Bank Tabungan Negara (BTN)" },
    { id: 6, name: "Bank Danamon" },
    { id: 7, name: "Bank CIMB Niaga" },
    { id: 8, name: "Bank OCBC NISP" },
    { id: 9, name: "Bank Maybank Indonesia" },
    { id: 10, name: "Bank Panin" },
    { id: 11, name: "Bank UOB Indonesia" },
    { id: 12, name: "Bank Permata" },
    { id: 13, name: "Bank BTPN" },
    { id: 14, name: "Bank Mega" },
    { id: 15, name: "Bank Sinarmas" },
    { id: 16, name: "Bank Maspion" },
    { id: 17, name: "Bank Mayapada" },
    { id: 18, name: "Bank Bukopin" },
    { id: 19, name: "Bank BRI Syariah" },
    { id: 20, name: "Bank Muamalat Indonesia" },
    { id: 21, name: "Bank Victoria International" },
    { id: 22, name: "Bank ANZ Indonesia" },
    { id: 23, name: "Bank DBS Indonesia" },
    { id: 24, name: "Bank HSBC Indonesia" },
    { id: 25, name: "Bank Rabobank International Indonesia" },
    { id: 26, name: "Bank Woori Saudara" },
    { id: 27, name: "Bank Capital Indonesia" },
    { id: 28, name: "Bank BCA Syariah" },
    { id: 29, name: "Bank BNI Syariah" },
    { id: 30, name: "Bank Mega Syariah" },
    { id: 31, name: "Bank BTPN Syariah" },
    { id: 32, name: "Bank CIMB Niaga Syariah" },
    { id: 33, name: "Bank Syariah Mandiri" },
    { id: 34, name: "Bank Panin Dubai Syariah" },
    { id: 35, name: "Bank Victoria Syariah" },
    { id: 36, name: "Bank JTrust" },
    { id: 37, name: "Bank Index Selindo" },
    { id: 38, name: "Bank Ganesha" },
    { id: 39, name: "Bank Royal Indonesia" },
    { id: 40, name: "Bank Ina Perdana" },
  ],
}));

export default useBanksStore;
