name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 62.171.177.93
        username: root
        password: ridwan174
        script: |
          cd /root/V4-Elog/
          git pull origin main
          npm install
          npm run build
